# Generated by Django 5.1 on 2024-10-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='current_price',
        ),
    ]
